class NotesData {

  final String semester;
  final List<String> subjectNames;
  final List<String> pdfURL;



  NotesData(this.semester,this.subjectNames, this.pdfURL);

}

NotesData physicsCycle = NotesData('Physics Cycle',['Calculus & Linear Algebra M-1','Engineering Physics','Basic Electrical Engineerin','Elements of Civil Engineering','Engineering Gaphics'],['https://drive.google.com/drive/folders/1Lis9bieuOiyBhNT18MVPGmGpjTk7K0NM?usp=sharing','https://drive.google.com/drive/folders/1IzCvN5h5evvbcxoLDLBjHyrEcnh0jCJ7?usp=sharing','https://drive.google.com/drive/folders/1eX3kUttstkz5CIlokN5PCbjOIOXeBrLd?usp=sharing','https://drive.google.com/drive/folders/1EjwcplKJRO48b3hRgxs5W8VDTBN6JB5i?usp=sharing','https://mrcet.com/downloads/hs/Engineering%20Graphics%20Manual%20final.pdf']);

NotesData chemistryCycle = NotesData('Chemistry Cycle', ['Advanced Calculus M-2','Engineering Chemistry','C Programming for Problem Solving','Basic Electronics','Elements of Mechanical Engineering'], ['https://drive.google.com/drive/folders/1kYYKGCtT-hWhcmnmiTu0sTPbupydhGu1?usp=sharing','https://drive.google.com/drive/folders/108SiyObuUV5G7FIpqsIzY7SQSDC1g1u1?usp=sharing','https://drive.google.com/drive/folders/1VL7T-SSIcCLq4sy_DG9Cebk9KXGGt4RL?usp=sharing','https://drive.google.com/drive/folders/1WGIzNengY0nqaNigzqj6oPXpTheZPZqv?usp=sharing','https://drive.google.com/drive/folders/1zM-ao3N2xUZsXNeJw94AgotswxOLEssP?usp=sharing']);

NotesData thirdSem = NotesData('3', ['Data Structures','Analog & Digital Electronics', 'Computer Organization','Software Engineering','Discrete Mathematics'], ['https://drive.google.com/drive/folders/1zEIG2Y2AIscKkuoSt7Kpx3-Gm03qb4ua?usp=sharing','https://drive.google.com/drive/folders/1dTlmo4w5V6hh3Y-rDL0aB_YBqRv_0FDF?usp=sharing','https://drive.google.com/drive/folders/1JvaqHGNLdXhqStYVdFHBMTM37vgjpC0d?usp=sharing','https://drive.google.com/drive/folders/1kCku6G6rEWKQnH8CWEGLqXsJl_j4dkMf?usp=sharing', 'https://drive.google.com/drive/folders/1nn7pGZbDtI4qI0xKfa-nFGD6NSmCSbAY?usp=sharing']);

NotesData fourthSem = NotesData('4', ['Design Analysis of Algorithm','Operating System','Micro-controller & Micro-processor','Object Oriented Concepts','Data Communications'], ['https://drive.google.com/drive/folders/1DChej1By7ZHhsok8DSY3P8UCgVExapA_?usp=sharing','https://drive.google.com/drive/folders/1EsuRE3XDHIJiwHP5nNhj0LWsMr-SHKRe?usp=sharing','https://drive.google.com/drive/folders/1J4UHQdSHiZzsvfFN4Uz6qr66hWki8BiN?usp=sharing','https://drive.google.com/drive/folders/1l8ifLw3LFNlJFdB7GXQ_-N6BPIO40dsU?usp=sharing','https://drive.google.com/drive/folders/1Z2gPsYFi4PDbCuW42oz6tiBa614Df_ff?usp=sharing']);

NotesData fifthSem = NotesData('5',['Management & Entrepreneurship for IT Industry','Computer Networks & Security','Database Management System','Automata Theory & Computability','Python Application Programming'],['https://drive.google.com/drive/folders/14f8vjXbDa4ka7VRAVarGnUlWEDVbtJmT?usp=sharing','https://drive.google.com/drive/folders/1tvAvMeqOtqB4rN5i7IqMu1NPXHlA0Xdl?usp=sharing','https://drive.google.com/drive/folders/1ZQt2eYI-WFhjUeV2fZM6eMSG88YB3Qb0?usp=sharing','https://drive.google.com/drive/folders/1ZbRjqkxsPs03FIktvcFCFx-bqPgNEHmE?usp=sharing','https://drive.google.com/drive/folders/14J2LUIKRZ6nkY5zowj8hqt4BBHIS39Qx?usp=sharing']);

NotesData sixthSem = NotesData('6', ['File Structures','Software Testing','Web Technology & its Application','Data Mining & Warehousing','Object Oriented Modeling & Design','Cloud Computing & its Applicaiton','Advanced Java & J2EE','Mobile Application Development','Programming in Java'], ['https://drive.google.com/drive/folders/152R-eZCZLFv2ktkkFY9eh1es-6B37YvQ?usp=sharing','https://drive.google.com/drive/folders/1Po3eQiFX8NGMp4G5tSVNsg1JQ0fWTzW5?usp=sharing','https://drive.google.com/drive/folders/10c21yRRfjfAiGvymy8pLVdm9uqGoQEZo?usp=sharing','https://drive.google.com/drive/folders/1P6J8gXNpmc3mFNdJRiVxXC-m_KjehClL?usp=sharing','https://drive.google.com/drive/folders/1JdoB305t4k-5ZWxEBiRXb7_k9tCqNYQM?usp=sharing','https://drive.google.com/drive/folders/1ffxOdNK-Xi0YBaRlBBwVlaPLSJll7Y36?usp=sharing','https://drive.google.com/drive/folders/12ohHy0SIXBpg3jC6Fbz4m7aRHKVbmyi_?usp=sharing','https://drive.google.com/drive/folders/1t9KiLMxhB5K-KPOauDjkXz8wvmJPwLro?usp=sharing','https://drive.google.com/drive/folders/1xCijCsSQpCA2CRL9tdOeOks2eOKDlZVC?usp=sharing']);

NotesData seventhSem = NotesData('7', ['Machine Learning','Big Data Analytics','User Interface Design','Artificial Intelligence','Cryptography Network Security','Introduction to Dot Net Framework','Advanced Computer Architecture','Storage Area Networks'], ['https://drive.google.com/drive/folders/1DrEszi_QMZ2E2ueOCx132-ItwFlimvWh?usp=sharing','https://drive.google.com/drive/folders/1heGcai2UuB32WeZAa-bigCCCud2MIf-k?usp=sharing','https://drive.google.com/drive/folders/1Gl_1c0hakNpkcFvIQHEMc4BZOdSnCm16?usp=sharing','https://drive.google.com/drive/folders/1XLfP20WOub1zajcEuCUF3h8grFi8Kz1Z?usp=sharing','https://drive.google.com/drive/folders/1CsoMjMXRn6K1OQ9vz7m77R58rt0dlpQH?usp=sharing','https://drive.google.com/drive/folders/1xq0vTvzD4fgtPZxx5Nn5xUwB8Kywk_Hs?usp=sharing','https://drive.google.com/drive/folders/11FuQFCVfYyz6K5j9h4s_DO0LGe5fHYeR?usp=sharing','https://drive.google.com/drive/folders/1cVdkznWp-zZwj6F_gk13Towt8QVxFAgW?usp=sharing']);

NotesData eigthSem = NotesData('8', ['Internet of Things','Mobile Computing','System Modelling & Simulation'], ['https://drive.google.com/drive/folders/1VRibwXiqsC8chtOM4u2FarNoo9XTUqhr?usp=sharing','https://drive.google.com/drive/folders/1Eiua31QPuW8IOYiOxpLx-61a_0Sy_omu?usp=sharing','https://drive.google.com/drive/folders/1MVFhOVagMtnt5LQ3mqbxBVqkaFLTU_se?usp=sharing']);