List quotes = [
  '“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.”',
  '“First, solve the problem. Then, write the code.”',
  '“Experience is the name everyone gives to their mistakes.”',
  '“ In order to be irreplaceable, one must always be different”',
  '“Java is to JavaScript what car is to Carpet.”',
  '“Knowledge is power.” ',
  '“Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.” ',
  '“Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away.” ',
  '“ Code is like humor. When you have to explain it, it’s bad.” ',
  '“Fix the cause, not the symptom.” ',
  '“Talk is cheap. Show me the code.”',
  '“Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live”',
  '“Truth can only be found in one place: the code.”',
  '“Give a man a program, frustrate him for a day. Teach a man to program, frustrate him for a lifetime.”',
  '“How you look at it is pretty much how you\'ll see it”',
  '“The most disastrous thing that you can ever learn is your first programming language.”',
  '“The most important property of a program is whether it accomplishes the intention of its user.”',
  'The best thing about a boolean is even if you are wrong, you are only off by a bit.',
  'Without requirements or design, programming is the art of adding bugs to an empty text file.',
  'There are only two kinds of programming languages: those people always bitch about and those nobody uses.',
  'In order to understand recursion, one must first understand recursion.',
  'The trouble with programmers is that you can never tell what a programmer is doing until it’s too late.',
];

List authors = [
  '– Martin Fowler',
  '– John Johnson',
  '– Oscar Wilde',
  '– Coco Chanel',
  '– Chris Heilmann',
  '– Francis Bacon',
  '– Dan Salomon',
  '– Antoine de Saint-Exupery',
  '– Cory House',
  '– Steve Maguire',
  '― Linus Torvalds',
  '― John Woods',
  '― Robert C. Martin',
  '― Muhammad Waseem',
  '― Rasheed Ogunlaru',
  '― Alan Kay',
  '― C.A.R. Hoare',
  '― Anonymous',
  '― Louis Srygley',
  '― Bjarne Stroustrup',
  '― Anonymous',
  '― Seymour Cray',
];