class TopicModel {

  final String topicName;
  final List<String> questionName;
  final List<String> url;

  TopicModel(this.topicName, this.questionName, this.url);

}

TopicModel array = new TopicModel('Array', ['Reverse the array','Find the maximum and minimum element in an array','Find the "Kth" max and min element of an array','Given an array which consists of only 0, 1 and 2. Sort the array without using any sorting algo','Move all the negative elements to one side of the array','Find the Union and Intersection of the two sorted arrays.','Write a program to cyclically rotate an array by one.','find Largest sum contiguous Subarray [V. IMP]','	Minimise the maximum difference between heights [V.IMP]','Minimum no. of Jumps to reach end of an array','find duplicate in an array of N+1 Integers'],['https://www.geeksforgeeks.org/write-a-program-to-reverse-an-array-or-string/','https://www.geeksforgeeks.org/maximum-and-minimum-in-an-array/','https://practice.geeksforgeeks.org/problems/kth-smallest-element/0','https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/0','https://www.geeksforgeeks.org/move-negative-numbers-beginning-positive-end-constant-extra-space/','https://practice.geeksforgeeks.org/problems/union-of-two-arrays/0','https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one/0','https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0','https://practice.geeksforgeeks.org/problems/minimize-the-heights3351/1','https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0','https://leetcode.com/problems/find-the-duplicate-number/'],);

TopicModel string = new TopicModel('String', ['Reverse a String','Check whether a String is Palindrome or not','Find Duplicate characters in a string','Why strings are immutable in Java?','Write a Code to check whether one string is a rotation of another','Write a Program to check whether a string is a valid shuffle of two strings or not','Count and Say problem','Write a program to find the longest Palindrome in a string.[ Longest palindromic Substring]','Find Longest Recurring Subsequence in String','Print all Subsequences of a string.','Print all the permutations of the given string'], ['https://leetcode.com/problems/reverse-string/','https://practice.geeksforgeeks.org/problems/palindrome-string0817/1','https://www.geeksforgeeks.org/print-all-the-duplicates-in-the-input-string/','https://www.baeldung.com/java-string-immutable','https://www.geeksforgeeks.org/a-program-to-check-if-strings-are-rotations-of-each-other/','https://www.programiz.com/java-programming/examples/check-valid-shuffle-of-strings','https://leetcode.com/problems/count-and-say/','https://practice.geeksforgeeks.org/problems/longest-palindrome-in-a-string/0','https://practice.geeksforgeeks.org/problems/longest-repeating-subsequence/0','https://www.geeksforgeeks.org/print-subsequences-string/','https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string/0'],);

TopicModel matrix = new TopicModel('Matrix',['Spiral traversal on a Matrix','Search an element in a matrix','Find median in a row wise sorted matrix','	Find row with maximum no. of 1\'s','Print elements in sorted order using row-column wise sorted matrix','Maximum size rectangle','Find a specific pair in matrix','Rotate matrix by 90 degrees','Kth smallest element in a row-cpumn wise sorted matrix','Common elements in all rows of a given matrix'], ['https://practice.geeksforgeeks.org/problems/spirally-traversing-a-matrix/0','https://leetcode.com/problems/search-a-2d-matrix/','https://practice.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1','https://practice.geeksforgeeks.org/problems/row-with-max-1s0023/1','https://practice.geeksforgeeks.org/problems/sorted-matrix/0','https://practice.geeksforgeeks.org/problems/max-rectangle/1','https://www.geeksforgeeks.org/find-a-specific-pair-in-matrix/','https://www.geeksforgeeks.org/rotate-a-matrix-by-90-degree-in-clockwise-direction-without-using-any-extra-space/','https://practice.geeksforgeeks.org/problems/kth-element-in-matrix/1','https://www.geeksforgeeks.org/common-elements-in-all-rows-of-a-given-matrix/']);

TopicModel binaryTree = new TopicModel('Binary Tree',['level order traversal','Reverse Level Order traversal','Height of a tree','Diameter of a tree','Mirror of a tree','Inorder Traversal of a tree both using recursion and Iteration','Preorder Traversal of a tree both using recursion and Iteration','Postorder Traversal of a tree both using recursion and Iteration','Left View of a tree','Right View of Tree','Top View of a tree'], ['https://practice.geeksforgeeks.org/problems/level-order-traversal/1','https://practice.geeksforgeeks.org/problems/reverse-level-order-traversal/1','https://practice.geeksforgeeks.org/problems/height-of-binary-tree/1','https://practice.geeksforgeeks.org/problems/diameter-of-binary-tree/1','https://www.geeksforgeeks.org/create-a-mirror-tree-from-the-given-binary-tree/','https://www.techiedelight.com/inorder-tree-traversal-iterative-recursive/','https://www.techiedelight.com/preorder-tree-traversal-iterative-recursive/','https://www.techiedelight.com/postorder-tree-traversal-iterative-recursive/','https://practice.geeksforgeeks.org/problems/left-view-of-binary-tree/1','https://practice.geeksforgeeks.org/problems/right-view-of-binary-tree/1','https://practice.geeksforgeeks.org/problems/top-view-of-binary-tree/1']);

TopicModel linkedList = new TopicModel('Linked List',['Write a Program to reverse the Linked List. (Both Iterative and recursive)','Reverse a Linked List in group of Given Size. [Very Imp]','Write a program to Detect loop in a linked list.','Write a program to Delete loop in a linked list.','Find the starting point of the loop.','Remove Duplicates in a sorted Linked List.','Remove Duplicates in a Un-sorted Linked List.','Write a Program to Move the last element to Front in a Linked List.','Add “1” to a number represented as a Linked List.','Add two numbers represented by linked lists.','	Intersection of two Sorted Linked List.'],['https://www.geeksforgeeks.org/reverse-a-linked-list/','https://practice.geeksforgeeks.org/problems/reverse-a-linked-list-in-groups-of-given-size/1','https://practice.geeksforgeeks.org/problems/detect-loop-in-linked-list/1','https://practice.geeksforgeeks.org/problems/remove-loop-in-linked-list/1','https://www.geeksforgeeks.org/find-first-node-of-loop-in-a-linked-list/','https://practice.geeksforgeeks.org/problems/remove-duplicate-element-from-sorted-linked-list/1','https://practice.geeksforgeeks.org/problems/remove-duplicates-from-an-unsorted-linked-list/1','https://www.geeksforgeeks.org/move-last-element-to-front-of-a-given-linked-list/','https://practice.geeksforgeeks.org/problems/add-1-to-a-number-represented-as-linked-list/1','https://practice.geeksforgeeks.org/problems/add-two-numbers-represented-by-linked-lists/1','https://practice.geeksforgeeks.org/problems/intersection-of-two-sorted-linked-lists/1'],);

TopicModel bitManipulation = new TopicModel('Bit Manipulation',['Count set bits in an integer','Find the two non-repeating elements in an array of repeating elements','Count number of bits to be flipped to convert A to B','Count total set bits in all numbers from 1 to n','Program to find whether a no is power of two','Find position of the only set bit','Copy set bits in a range','Divide two integers without using multiplication, division and mod operator','Calculate square of a number without using *, / and pow()','Power Set'],['https://practice.geeksforgeeks.org/problems/set-bits0143/1','https://practice.geeksforgeeks.org/problems/finding-the-numbers0215/1','https://practice.geeksforgeeks.org/problems/bit-difference/0','https://practice.geeksforgeeks.org/problems/count-total-set-bits/0','https://practice.geeksforgeeks.org/problems/power-of-2/0','https://practice.geeksforgeeks.org/problems/find-position-of-set-bit3706/1','https://www.geeksforgeeks.org/copy-set-bits-in-a-range/','https://www.geeksforgeeks.org/divide-two-integers-without-using-multiplication-division-mod-operator/','https://www.geeksforgeeks.org/calculate-square-of-a-number-without-using-and-pow/','https://practice.geeksforgeeks.org/problems/power-set4302/1'],);